### ISSUE TITLE
why RTX3060 with Ampere architecture is not supported?

### ISSUE THREAD

**Issue by liuw666-bruce** [microsoft/ark#203]
For ark v0.5.0, the file named docs/install.md shows all supported NVIDIA GPU include "Volta (CUDA >= 11.1) / Ampere (CUDA >= 11.1) / Hopper (CUDA >= 12.0)", but my RTX3060 (Ampere) with capability 8.6 cannot work with ark. Why? I also found below code in the file ark/ops/ops_common.cc, it means only GPU with capability 6.0/7.0/8.0/9.0 are supported, right? 

pArchType op_arch_from_string(const std::string &arch) {
    if (arch == "cuda_60") {
        return OP_ARCH_CUDA_60;
    } else if (arch == "cuda_70") {
        return OP_ARCH_CUDA_70;
    } else if (arch == "cuda_80") {
        return OP_ARCH_CUDA_80;
    } else if (arch == "cuda_90") {
        return OP_ARCH_CUDA_90;
    } else if (arch == "rocm_90a") {
        return OP_ARCH_ROCM_90A;
    } else if (arch == "rocm_942") {
        return OP_ARCH_ROCM_942;
    }
    return OP_ARCH_UNKNOWN;
}

**Comment by Binyang2014** [comment]
For different OPs, we have some manual tuned configurations to run these ops efficiently.  We only tune the configuration for some of the GPU architecture, others are not supported yet.
