### ISSUE TITLE
transformer_test.py prompts [AttributeError: 'Model' object has no attribute 'tensor']

### ISSUE THREAD

**Issue by elliottall** [microsoft/ark#204]
ENV: 2 A100s and ran the provided image from ARK version 0.3.0 to 0.5.0.
BUG: When running $python3 transformer_test.py in examples/transformer, it will prompt **AttributeError: 'Model' object has no attribute 'tensor'.**
e.g. ARK 0.5.0:
Traceback (most recent call last):
File "examples/transformer/transformer_test.py", line 560, in <module>
test_PoswiseFeedForwardNet()
File "examples/transformer/transformer_test.py", line 15, in test_PoswiseFeedForwardNet
input_tensor= model.tensor(

AttributeError: 'Model' object has no attribute 'tensor
Please tell us how to solve this problem, thank you.

**Comment by elliottall** [comment]
PS:
OS: Ubuntu 18.04.1
Compiler: g++(9.4), cmake (3.26.1)
NVCC: 11.8
Linux kernel: 5.4.0-42(generic)

**Comment by chhwang** [comment]
@elliottall Sorry, `examples/transformer` is not being maintained right now. You can find a similar transformer example from `examples/llama`.

**Comment by elliottall** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
